apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: akki
  name: akki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akki
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: akki
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
